"""All user-facing text, one string per concept.

Stage 4 canonical terms (change wording HERE, not in tabs):
"Text to speak" · "Voice" (preset speaker) · "Reference audio" /
"Reference transcript" · "Style instructions (optional)" ·
"Voice description" · "Generated audio" · "Voice Clone" (mode name).
"""
from config import LANGUAGE_AUTO as CONFIG_LANGUAGE_AUTO

# --- App shell ---
APP_TITLE = "Qwen3-TTS MLX Studio"
APP_HEADER_HTML = (
    "<div class='app-header'>"
    "<h1>Qwen3-TTS MLX Studio</h1>"
    "<p class='subtitle'>Local AI Text-to-Speech &middot; MLX &middot; Apple Silicon</p>"
    "</div>"
)
STATUS_READY = "Ready"

# --- Shared generation inputs ---
TEXT_TO_SPEAK = "Text to speak"
TEXT_PLACEHOLDER = "Enter the text you want spoken…"
TIP_TEXT_LENGTH = (
    "_Tip: 1–4 sentences work best. Long or number-heavy text can run away — "
    "the Stop button or the auto-stop timeout will end it, keeping partial audio._"
)
LANGUAGE = "Language"
LANGUAGE_AUTO = CONFIG_LANGUAGE_AUTO  # UI label for automatic detection
GENERATE = "Generate"

# --- Voice cloning extras (Stage 2) ---
TRIM_REF_LABEL = "Trim silence from reference (recommended)"
REP_PENALTY_CLONE_INFO = "Voice cloning always uses at least 1.5"

# --- Shared output column ---
OUTPUT = "Generated audio"
SAVE_AUDIO = "Save Audio"
SAVE_PATH_PLACEHOLDER = "Save path appears here…"

# --- Batch accordion ---
BATCH_ACCORDION = "Batch Mode"
SPLIT_MODE = "Split text by"
SILENCE_GAP = "Silence between segments (ms)"
GENERATE_BATCH = "Generate Batch"
BATCH_RESULTS = "Segments"
COMBINED_OUTPUT = "Generated audio (combined)"
SAVE_COMBINED = "Save Combined Audio"
BATCH_STATUS = "Batch Status"

# --- Save-to-library accordion ---
LIB_SAVE_ACCORDION = "Save to Voice Library"
VOICE_NAME = "Voice Name"
SAVE_VOICE_TO_LIBRARY = "Save Voice to Library"
LIB_STATUS_PLACEHOLDER = "Library status…"

# --- Custom Voice tab ---
TAB_CUSTOM_VOICE = "Custom Voice"
CV_SPEAKER = "Voice"
CV_INSTRUCT = "Style instructions (optional)"
CV_INSTRUCT_PLACEHOLDER = "e.g. Speak warmly, Sound excited..."

# --- Voice Design tab ---
TAB_VOICE_DESIGN = "Voice Design"
VD_INSTRUCT = "Voice description"
VD_INSTRUCT_PLACEHOLDER = "e.g. A deep, calm male narrator with a British accent"
VD_LIB_NAME_PLACEHOLDER = "my_narrator"

# --- Voice Clone tab ---
TAB_VOICE_CLONE = "Voice Clone"
VC_NOTICE_HTML = (
    "<div class='info-notice'>"
    "<strong>The reference transcript must exactly match what is spoken in the audio.</strong> "
    "Use a clean 3–30 second clip for best results."
    "</div>"
)
VC_LIBRARY_VOICE = "Load from Library"
VC_REF_AUDIO = "Reference audio"
VC_TRANSCRIBE = "Transcribe Reference"
VC_TRANSCRIBE_HINT_HTML = "<div class='text-hint'>Auto-fills the transcript using on-device speech recognition</div>"
VC_REF_TEXT = "Reference transcript (required)"
VC_REF_TEXT_PLACEHOLDER = "The exact words spoken in the reference audio"
VC_LIB_NAME_PLACEHOLDER = "my_clone"

# --- Transcription tab ---
TAB_TRANSCRIPTION = "Transcription"
ASR_NOTICE_HTML = (
    "<div class='info-notice'>"
    "Transcribe audio files locally using on-device speech recognition. "
    "Supports up to ~20 minutes of audio."
    "</div>"
)
ASR_AUDIO = "Audio to transcribe"
ASR_TRANSCRIBE = "Transcribe"
ASR_OUTPUT = "Transcript"
ASR_SAVE_TXT = "Save as .txt"
ASR_SAVE_PLACEHOLDER = "Save path appears here…"
ASR_INFO_MD = (
    "**Model:** Qwen3-ASR-1.7B-8bit\n\n"
    "**Supported languages:** Auto-detect, English, Chinese, Japanese, Korean, "
    "German, French, Russian, Portuguese, Spanish, Italian\n\n"
    "**Max duration:** ~20 minutes per file"
)
ASR_NO_AUDIO_WARN = "Upload or record audio first."
ASR_NO_AUDIO = "No audio"
ASR_NOTHING_TO_SAVE_WARN = "No transcription to save."
ASR_NOTHING_TO_SAVE = "Nothing to save"
ASR_SAVED = "Saved: {path}"

# --- YT Voice Clone tab ---
TAB_YT = "YT Voice Clone"
YT_NOTICE_HTML = (
    "<div class='info-notice'>"
    "Clone any voice from YouTube: fetch a video, pick a timestamp range, "
    "auto-extract the clip with aligned transcript, then generate."
    "</div>"
)
YT_STEP_1 = "**Step 1 — Video URL**"
YT_URL_PLACEHOLDER = "https://www.youtube.com/watch?v=..."
YT_FETCH = "Fetch Video Info"
YT_STEP_2 = "**Step 2 — Select Clip**"
YT_START = "Start time (mm:ss)"
YT_START_PLACEHOLDER = "blank = beginning"
YT_END = "End time (mm:ss)"
YT_END_PLACEHOLDER = "blank = end of video"
YT_EXTRACT = "Extract Clip"
YT_STEP_3 = "**Step 3 — Review Transcript**"
YT_TRANSCRIPT = "Reference transcript"
YT_TRANSCRIPT_INFO = "Auto-filled from subtitles — edit if needed"
YT_TRANSCRIPT_PLACEHOLDER = "Transcript appears here after extraction, or enter manually…"
YT_TRANSCRIBE = "Transcribe Clip"
YT_TRANSCRIBE_HINT_HTML = "<div class='text-hint'>Use speech recognition when subtitles are unavailable or inaccurate</div>"
YT_STEP_4 = "**Step 4 — Generate & Save**"
YT_VOICE_NAME = "Voice name (saved to library)"
YT_VOICE_NAME_PLACEHOLDER = "yt_speaker"
YT_CLONE = "Clone & Save to Library"
YT_THUMBNAIL = "Video thumbnail"
YT_INFO_EMPTY = "_Video info appears here after fetching._"
YT_CLIP_PREVIEW = "Reference clip preview"
YT_STATUS = "Status"
YT_ENTER_URL = "Enter a YouTube URL"
YT_ENTER_URL_MD = "_Enter a URL above._"
YT_SUBS_MANUAL = "Manual subtitles"
YT_SUBS_AUTO = "Auto-generated subtitles (may need editing)"
YT_SUBS_NONE = "No subtitles — enter transcript manually"
YT_FETCHED = "✓ Fetched: {title}"
YT_FETCH_FIRST = "Fetch video info first (Step 1)"
YT_BAD_START = "Bad start time: {err}"
YT_ENTER_END_WARN = "Enter an end time — video duration unknown."
YT_ENTER_END = "Enter an end time"
YT_BAD_END_WARN = "Invalid end time — use mm:ss"
YT_BAD_END = "Enter a valid end time"
YT_END_BEFORE_START_WARN = "End time must be after start time."
YT_END_BEFORE_START = "End must be after start"
YT_CLIP_TOO_SHORT_WARN = "Clip must be at least 3 seconds."
YT_CLIP_TOO_SHORT = "Clip too short (min 3 s)"
YT_CLIP_CAPPED_WARN = "Clip capped at 60 seconds."
YT_CLIP_LONG_WARN = "Clip is {secs:.0f}s — 5-20 s gives best clone quality."
YT_END_BEYOND_WARN = "End time exceeds video duration ({secs:.0f}s)."
YT_END_BEYOND = "End time beyond video end"
YT_EXTRACT_PROGRESS_START = "Starting…"
YT_EXTRACT_PROGRESS_TRANSCRIPT = "Extracting transcript…"
YT_EXTRACT_PROGRESS_DONE = "Done"
YT_EXTRACTED = "✓ {secs:.1f}s clip extracted — {note}"
YT_TRANSCRIPT_FILLED = "transcript auto-filled"
YT_EXTRACT_FAILED = "Extraction failed: {err}"
YT_NO_CLIP_WARN = "Extract a clip first (Step 2)."
YT_NO_CLIP = "No clip to transcribe"
YT_REQUIRED = "Required: {items}"
YT_REQ_TEXT = "text to speak"
YT_REQ_CLIP = "reference clip (extract one first)"
YT_REQ_TRANSCRIPT = "reference transcript"
YT_REQ_NAME = "voice name"
YT_STOPPED = "Stopped"
YT_SAVED_OK = "✓ {msg}"

# --- Script Mode tab ---
TAB_SCRIPT = "Script Mode"
SM_NOTICE_HTML = (
    "<div class='info-notice'>"
    "<strong>Multi-Speaker Script</strong> &nbsp;—&nbsp; "
    "Each line: <code>SPEAKER: Dialogue text</code> &nbsp; Lines without a label are narration."
    "</div>"
)
SM_SCRIPT = "Script"
SM_SCRIPT_PLACEHOLDER = (
    "NARRATOR: Once upon a time, there lived a curious inventor.\n"
    "EMMA: Father, look what I found in the attic!\n"
    "FATHER: That is something I built a long time ago."
)
SM_PARSE = "Parse Script"
SM_SILENCE = "Silence between lines (ms)"
SM_PARSE_RESULT = "Parse result"
SM_ASSIGNMENTS_HEADER = "### Voice Assignments"
SM_SLOT_MODE = "Speaker {n} voice type"
SM_SLOT_INSTRUCT = "Style instructions / voice description"
SM_SLOT_INSTRUCT_PLACEHOLDER = "Style instructions or a voice description"
SM_SLOT_LIBRARY = "Library voice"
SM_GENERATE = "Generate Script"
SM_BREAKDOWN = "Per-line breakdown"
SM_TABLE_EMPTY = "*Results will appear after generation.*"
SM_STATUS = "Status"
SM_TABLE_HEADERS = ["Line", "Speaker", "Text", "Status"]
SM_NO_RESULTS = "*No results.*"
SM_ENTER_SCRIPT_WARN = "Enter a script first."
SM_ENTER_SCRIPT_MD = "*Enter a script first.*"
SM_ENTER_SCRIPT = "Enter script first"
SM_PARSE_FIRST_WARN = "Parse the script and assign voices first."
SM_PARSE_FIRST_MD = "*Parse the script and assign voices first.*"
SM_PARSE_FIRST = "Parse script first"
SM_SUMMARY_HEAD = "Found {speakers} speakers, {lines} lines:"
SM_SUMMARY_LINE = "  {speaker}: {count} lines"

# --- Streaming / cancel (Stage 3) ---
STOP = "Stop"
STOPPING = "Stopping…"
GENERATING_STATUS = "Generating… {secs:.1f}s"
STOPPED_KEPT = "Stopped — kept {secs:.1f}s of partial audio"
TIMED_OUT_KEPT = "Timed out after {timeout}s — kept {secs:.1f}s of partial audio"
TIMEOUT_MSG = "Generation timed out — lower Max Tokens or shorten the text"
BATCH_SEGMENT_PROGRESS = "Segment {done}/{total} · {secs:.1f}s audio"
BATCH_STOPPED = "Stopped — completed {done}/{total} segments"
SCRIPT_LINE_PROGRESS = "Line {done}/{total} · {secs:.1f}s audio"
SCRIPT_STOPPED = "Stopped — completed {done}/{total} lines"
ASR_LOADING = "Loading ASR model..."
TRANSCRIBING = "Transcribing… {words} words"
TRANSCRIBE_STOPPED = "Stopped — partial transcript kept"
TIMEOUT_SLIDER_INFO = "Auto-stops a run after this many seconds, keeping partial audio"

# --- History tab ---
TAB_HISTORY = "History"
HIST_TABLE_LABEL = "Generation History"
HIST_TABLE_HEADERS = ["ID", "Time", "Mode", "Text", "Duration"]
HIST_ENTRY_ID = "Entry ID"
HIST_ENTRY_PLACEHOLDER = "Paste an entry ID to preview or manage it"
HIST_PREVIEW = "Preview"
HIST_DELETE = "Delete Entry"
HIST_CLEAR = "Clear All History"
HIST_VIEW_SETTINGS = "View generation settings"
HIST_SETTINGS_LABEL = "Generation settings"
HIST_STATUS_PLACEHOLDER = "Status…"
HIST_SELECT_FIRST = "Select an entry first"
HIST_DELETED = "Deleted entry {entry_id}"
HIST_CLEARED = "History cleared"
HIST_NOT_FOUND = "Entry not found"
HIST_AUDIO_NOT_FOUND = "Audio not found"
HIST_AUDIO_MISSING_WARN = "Audio not found for this entry."

# --- Voice Library tab ---
TAB_LIBRARY = "Voice Library"
LIB_TABLE_LABEL = "Saved Voices"
LIB_TABLE_HEADERS = ["Name", "Source", "Language", "Description"]
LIB_SELECTED = "Voice name"
LIB_SELECTED_PLACEHOLDER = "Type or paste a voice name"
LIB_PREVIEW = "Preview"
LIB_DELETE = "Delete"
LIB_RENAME_TO = "Rename to"
LIB_RENAME_PLACEHOLDER = "new_name"
LIB_RENAME = "Rename"
LIB_PREVIEW_AUDIO = "Reference audio preview"
LIB_STATUS_TEXT_PLACEHOLDER = "Status…"
LIB_IMPORT_HEADER = "### Import Voice"
LIB_IMPORT_TRANSCRIPT = "Reference transcript"
LIB_IMPORT_NAME = "Voice name"
LIB_IMPORT_NAME_PLACEHOLDER = "imported_voice"
LIB_IMPORT = "Import Voice"
LIB_SELECT_FIRST = "Select a voice first"
LIB_DELETED = "Deleted '{name}'"
LIB_VOICE_NOT_FOUND = "Voice '{name}' not found"
LIB_ENTER_NEW_NAME = "Enter a new name"
LIB_RENAMED = "Renamed '{old}' to '{new}'"
LIB_RENAME_FAILED = "Rename failed (name may already exist)"
LIB_IMPORTED = "Imported '{name}'"
LIB_IMPORT_NO_AUDIO_WARN = "Upload audio to import."
LIB_IMPORT_NO_AUDIO = "Upload audio first"
LIB_IMPORT_NO_NAME_WARN = "Enter a name for the imported voice."
LIB_IMPORT_NO_NAME = "Enter a name"
LIB_IMPORT_NO_TRANSCRIPT_WARN = "Transcript required for imported voice."
LIB_IMPORT_NO_TRANSCRIPT = "Enter transcript"
LIB_IMPORTED_DESCRIPTION = "Imported voice"

# --- Settings tab ---
TAB_SETTINGS = "Settings"
SET_MODEL_HEADER = "### Model"
SET_MODEL_SIZE = "Model size"
SET_QUANT = "Quantization"
SET_QUANT_INFO = "Smaller = less memory, slightly lower quality"
SET_LOADED_MODEL = "Loaded model"
SET_UNLOAD = "Unload Model / Free RAM"
SET_REF_HEADER = "### Reference Audio"
SET_DENOISE = "Reduce reference background noise"
SET_DENOISE_INFO = "Uses the DeepFilterNet model (8 MB, downloads on first use) on Voice Clone references"
SET_LANGUAGE_HEADER = "### Language"
SET_DEFAULT_LANGUAGE = "Default language"
SET_JIT = "Speed up repeat runs"
SET_JIT_INFO = "Compiles the model after the first generation; changing this reloads the model"
SET_CACHE_ACCORDION = "Model Cache & Speech Recognition"
SET_CACHE_HEADER = "### Model Cache"
SET_CACHE_DIR = "Model download folder"
SET_DELETE_MODELS = "Delete Downloaded Models"
SET_DELETE_PLACEHOLDER = "Models will be re-downloaded on next use."
SET_ASR_HEADER = "### Speech Recognition"
SET_ASR_STATUS = "Speech recognition model"
SET_ASR_NOT_LOADED = "Not loaded (loads on demand)"
SET_ASR_UNLOAD = "Unload Speech Recognition Model"
SET_GENERATION_HEADER = "### Generation"
SET_PRESET = "Generation presets"
SET_PRESET_INFO = "Presets fill the sliders below. Adjust freely afterward."
SET_TEMP = "Temperature"
SET_TEMP_INFO = "Higher = more varied delivery, lower = more consistent"
SET_TOP_K = "Top-K"
SET_TOP_K_INFO = "How many candidate sounds are considered each step — lower = safer"
SET_TOP_P = "Top-P"
SET_TOP_P_INFO = "Keeps only the most likely sounds — lower = more predictable"
SET_REP_PENALTY = "Repetition penalty"
SET_REP_PENALTY_INFO = "Discourages repeating sounds. Voice Clone always uses at least 1.5"
SET_MAX_TOKENS = "Max length (tokens)"
SET_MAX_TOKENS_INFO = "Upper limit on how long one generation may run — lower it if runs go on too long"
SET_TIMEOUT = "Auto-stop after (seconds)"
SET_BATCH_SIZE = "Batch size"
SET_BATCH_SIZE_INFO = "Segments generated in parallel (batch and Script Mode)"
SET_RESET = "Reset to Defaults"
SET_OUTPUT_HEADER = "### Output"
SET_OUTPUT_DIR = "Output folder"
SET_AUTOSAVE = "Auto-save generated audio"
SET_EXPORT_HEADER = "### Export Format"
SET_EXPORT_FORMAT = "Audio format"
SET_MP3_BITRATE = "MP3 bitrate (kbps)"
SET_POST_HEADER = "### Post-Processing"
SET_LOUDNORM = "Normalize loudness"
SET_LOUDNORM_INFO = "EBU R128 broadcast standard"
SET_TRIM_SILENCE = "Trim leading/trailing silence"
SET_STORAGE_ACCORDION = "Storage & Cache"
SET_YT_CACHE_HEADER = "### YT Cache"
SET_YT_CACHE_CLEAR = "Clear YT Cache"
SET_YT_CACHE_PLACEHOLDER = "Cache: {cache_dir}/"
SET_STORAGE_HEADER = "### Storage Paths"
SET_STORAGE_LIBRARY = "Voice Library"
SET_STORAGE_HISTORY = "History"
SET_APPLY = "Apply Settings"
SET_NO_MODEL = "No model loaded"
SET_MODEL_LOADED = "Loaded: {repo}"
SET_APPLIED = "Settings applied — {details}."
SET_APPLIED_SIZE_QUANT = "size: {size}, quant: {quant}"
SET_APPLIED_UNLOADED = "model unloaded"
SET_UNLOADED_MSG = "Model unloaded. RAM freed."
SET_ASR_UNLOADED_MSG = "Speech recognition model unloaded. RAM freed."
SET_YT_CACHE_CLEARED = "YT cache cleared — {n} entr{plural} removed"
SET_CACHE_DIR_MISSING = "Model download folder not found"
SET_DELETED_MODELS = "Deleted {n} model(s): {names}"
SET_DELETE_FAILED = "Failed to delete {n}: {details}"
SET_NO_MODELS_FOUND = "No Qwen3-TTS models found in cache"

# --- Table empty states ---
NO_VOICES = "*No voices saved.*"
NO_HISTORY = "*No history entries.*"
NO_ENTRIES = "*No entries.*"
